"""Init3

Revision ID: d42a8cde6746
Revises: 4f32b6de6f07
Create Date: 2023-07-06 11:29:35.263816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42a8cde6746'
down_revision = '4f32b6de6f07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
